<?php
/**
 * Plugin Name: Term-Pages
 * Description: Overwrites first page of term archives with a page.
 * Version: 1.0
 * Author: PALASTHOTEL <rezeption@palasthotel.de>
 * Author URI: http://www.palasthotel.de
 * Requires at least: 4.0
 * @copyright Copyright (c) 2016, Palasthotel
 */

/**
 * Generated by the WordPress Meta Box Generator at http://goo.gl/8nwllb
 * modified by Julia Krischik <julia.krischik@palasthotel.de>
 */
class Term_Pages {

	/**
	 * Class construct method. Adds actions to their respective WordPress hooks.
	 */
	public function __construct() {

	}
}
new Term_Pages;